build: false

environment:
  matrix:
  - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "python --version"

  - "pyton install pip"

  - "pip install poetry"
  - "poetry install"

test_script:
  - "pytest --cov"

