build: false

environment:
  matrix:
  - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install poetry"
  - "pip install -U pytest"
  - "poetry install"

test_script:
  - "pytest --cov"

